language:
- swift
osx_image: xcode10.2
if: tag IS blank
script:
- set -o pipefail && xcodebuild | xcpretty
- set -o pipefail && xcodebuild -project OpenCore\ Configurator.xcodeproj -scheme OpenCore\ Configurator -destination platform\=macOS test | xcpretty
before_deploy:
- cd build/Release
- COMMIT="$(git log --format=%h -1)"
- git tag $COMMIT
- zip -r -X OpenCore.zip OpenCore\ Configurator.app
- cd ..
- cd ..
- mv build/Release/OpenCore.zip "$COMMIT.zip"
deploy:
  provider: releases
  api_key:
    secure: pqVH8IkJEJmdW14M85esYP0vh9MUaTmKOoaScBm87Bo3HA5MngOwEZgIAxrXIIBy/SgyNIsStpvUMm7BTKZSaZom8GZDu2Wjsom1Y/CSEsX106t3U6g7jR7N8j/4/ytD/+Vh+pgsZRePjgfW4xRxO0IR6k36d3EySx10DT73TskvYKq0K5xv5KSC3TYxrrLcsHH87Oh6ML1tvihz37s9eshleJpuMS4D6zEx/GoblNCmSTSnlE985C9LAefl8EBEZYqTgdpYhLJsS2I70gX8lZNyiG22604hdsjkx6yR2tLAUBH0lxbrvLsesk5wgGgBOl9MMbr2hn/l8BlluIle26bamMBqKO/KsDUkvSgLTdkPwiUyYe6X1J/gNmzvv9WsYCrxmxVoc/UnpWSvkRB4VajIXgg+64oW8pajX6luLQ7MI+A3kDdoFEtmCccOfL1ypgbTQB3Qho9UPFGwhRjiV5CFlzGA4lgjunhsFI2YeiCa2kTcB8EYtQNxX8Vtbwm3nlpMwVLGQX5aeU8oxh+bzXV2y1gtHhzVScJokOJEM+/GDkL+oj/DsIC0WeYKrjLZvFoEmwX1+GO8SgwUrh/L9zLX81MwsfOve/+kKCWR1ACCYW5Nh20HHD663rUGOjLu4sRC6sG4ccy+NbRmuYYDp8p+SyuYc/j5y05kWs9MUI0=
  file: "$COMMIT.zip"
  skip_cleanup: true
